const $=id=>document.getElementById(id);
const PLACEHOLDER="Todavía no hay nada transcrito.";
const state={stream:null,recorder:null,recognition:null,audioContext:null,analyser:null,frame:null,wakeLock:null,chunks:[],recording:false,paused:false,startedAt:0,elapsed:0,timer:null,fragments:[],sessionId:null,deferredPrompt:null,recognitionLang:"es-UY",votes:{es:0,en:0}};
const STOP=new Set("a al algo algunas algunos ante antes como con contra cual cuando de del desde donde el ella ellas ellos en entre era es esa esas ese eso esos esta estaba estado estas este esto estos fue ha hay la las le les lo los mas me mi mis muy no nos o para pero por porque que se ser si sin sobre su sus tambien te tener tiene todo tu un una uno unos y ya yo eh emm mmm bueno tipo osea the and to of in is it that for on with as this be are was at or by an from not have has you we they he she i so well like yeah okay ok um uh".split(" "));
const ES=new Set("que para porque como pero entonces cuando donde esta esto una con por del los las".split(" "));
const EN=new Set("the and that with from this what when where because then have has are you your for".split(" "));
function norm(s=""){return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function words(t,keep=false){const a=(t.toLowerCase().match(/[a-záéíóúüñ0-9]{2,}/gi)||[]).map(norm);return keep?a:a.filter(w=>w.length>=3&&!STOP.has(w))}
function sentences(t){return(t.match(/[^.!?]+[.!?]?/g)||[]).map(s=>s.trim()).filter(Boolean)}
function esc(v=""){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function clean(t){return t.replace(/\b(eh+|emm+|mmm+|um+|uh+)\b[,. ]*/gi,"").replace(/\s{2,}/g," ").replace(/\s+([,.!?])/g,"$1").trim()}
function keys(t,n=12){const m=new Map;for(const w of words(t))m.set(w,(m.get(w)||0)+1);return[...m].sort((a,b)=>b[1]-a[1]||b[0].length-a[0].length).slice(0,n).map(([word,count])=>({word,count}))}
function language(t){let es=/[ñáéíóú¿¡]/i.test(t)?2:0,en=0;for(const w of words(t,true)){if(ES.has(w))es++;if(EN.has(w))en++}return en>es+1?"en-US":es>en+1?"es-UY":state.recognitionLang}
function format(ms){const x=Math.max(0,Math.floor(ms/1000)),h=String(Math.floor(x/3600)).padStart(2,"0"),m=String(Math.floor((x%3600)/60)).padStart(2,"0"),s=String(x%60).padStart(2,"0");return h+":"+m+":"+s}
function text(){return $("cleanTranscript").innerText.replace(PLACEHOLDER,"").trim()}
function setText(t){const b=$("cleanTranscript");b.innerHTML="";if(!t){b.innerHTML='<p class="placeholder">'+PLACEHOLDER+"</p>";return}for(const s of sentences(t)){const p=document.createElement("p");p.textContent=s;b.appendChild(p)}}
function header(t){$("headerStatus").textContent=t}
function updateTimer(){let ms=state.elapsed;if(state.recording&&!state.paused)ms+=Date.now()-state.startedAt;$("timer").textContent=format(ms)}
async function wake(){try{if("wakeLock"in navigator&&document.visibilityState==="visible")state.wakeLock=await navigator.wakeLock.request("screen")}catch{}}
function audioSession(){try{if(navigator.audioSession)navigator.audioSession.type="play-and-record"}catch{}}
async function start(){try{audioSession();state.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});state.sessionId=crypto.randomUUID?.()||String(Date.now());state.chunks=[];meter();recordAudio();recognize();state.recording=true;state.paused=false;state.startedAt=Date.now();state.elapsed=0;clearInterval(state.timer);state.timer=setInterval(updateTimer,250);wake();ui();header("Grabando")}catch(e){console.error(e);$("compatibilityNotice").classList.remove("hidden");$("compatibilityNotice").textContent="No pude activar el micrófono. Revisá el permiso y que estés usando HTTPS o localhost."}}
function recordAudio(){const pref=["audio/webm;codecs=opus","audio/mp4;codecs=mp4a.40.2","audio/mp4"].find(x=>MediaRecorder.isTypeSupported?.(x));state.recorder=new MediaRecorder(state.stream,pref?{mimeType:pref}:undefined);state.recorder.ondataavailable=e=>{if(e.data?.size)state.chunks.push(e.data)};state.recorder.onstop=()=>saveSession();state.recorder.start(1500)}
function best(r){let b=r[0];for(let i=1;i<r.length;i++)if((r[i].confidence||0)>(b.confidence||0))b=r[i];return b}
function recognize(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){$("qualityState").textContent="Sin transcripción en vivo en este navegador";return}const r=new R;r.continuous=true;r.interimResults=true;r.maxAlternatives=3;state.recognitionLang=$("languageSelect").value==="en-US"?"en-US":"es-UY";r.lang=state.recognitionLang;try{const topic=$("topicInput").value.trim();if(topic&&"phrases"in r&&window.SpeechRecognitionPhrase)r.phrases=[new SpeechRecognitionPhrase(topic,6),...keys(topic,6).map(k=>new SpeechRecognitionPhrase(k.word,4))]}catch{}r.onresult=e=>{let interim="";for(let i=e.resultIndex;i<e.results.length;i++){const a=best(e.results[i]),t=clean(a.transcript||"");if(!t)continue;if(e.results[i].isFinal)addFragment(t,a.confidence||0);else interim+=t+" "}$("interimTranscript").textContent=interim.trim()};r.onerror=e=>{if(!["no-speech","aborted"].includes(e.error))$("qualityState").textContent="Reconocimiento: "+e.error};r.onend=()=>{if(!state.recording||state.paused)return;r.lang=state.recognitionLang;setTimeout(()=>{try{r.start()}catch{}},180)};state.recognition=r;try{r.start()}catch{}}
function addFragment(t,confidence){const prev=state.fragments.at(-1)?.text||"";if(prev&&norm(prev)===norm(t))return;if(prev&&prev.length>20&&t.length>20){const a=prev.toLowerCase(),b=t.toLowerCase();if((a.includes(b)||b.includes(a))&&Math.abs(a.length-b.length)<25){if(b.length<=a.length)return;state.fragments.pop()}}state.fragments.push({text:t,confidence,keep:true,at:Date.now()});if($("languageSelect").value==="bilingual"){const d=language(t);d==="en-US"?state.votes.en++:state.votes.es++;if(state.votes.en>=2&&state.recognitionLang!=="en-US"){state.recognitionLang="en-US";state.votes={es:0,en:0};try{state.recognition.stop()}catch{}}else if(state.votes.es>=2&&state.recognitionLang!=="es-UY"){state.recognitionLang="es-UY";state.votes={es:0,en:0};try{state.recognition.stop()}catch{}}}reclassify();$("undoBtn").disabled=!state.fragments.length;autosave()}
function score(f,topic,global){const u=[...new Set(words(f.text))];if(!u.length)return 0;let tm=0,g=0;for(const w of u){if(topic.includes(w))tm++;g+=global.get(w)||0}return(tm/Math.max(2,Math.min(u.length,8)))*.45+Math.min(1,g/Math.max(4,u.length*2))*.25+Math.min(1,u.length/9)*.18+Math.min(1,(f.confidence||.5)/.75)*.12}
function reclassify(){const manual=$("topicInput").value.trim(),all=state.fragments.map(f=>f.text).join(" "),topic=keys(manual+" "+manual+" "+all,18).map(k=>k.word),global=new Map;for(const f of state.fragments)for(const w of words(f.text))global.set(w,(global.get(w)||0)+1);state.fragments.forEach((f,i)=>{const short=words(f.text).length<=2&&(f.confidence||.5)<.45;f.keep=!short&&(i<4||score(f,topic,global)>=.27)});setText(state.fragments.filter(f=>f.keep).map(f=>f.text).join(" "));renderRaw();insights()}
function pause(){if(!state.recording)return;if(!state.paused){state.paused=true;state.elapsed+=Date.now()-state.startedAt;try{state.recorder.pause()}catch{}try{state.recognition?.stop()}catch{}}else{state.paused=false;state.startedAt=Date.now();try{state.recorder.resume()}catch{}try{state.recognition?.start()}catch{}wake()}ui()}
function finish(){if(!state.recording)return;if(!state.paused)state.elapsed+=Date.now()-state.startedAt;state.recording=false;state.paused=false;try{state.recognition?.stop()}catch{}try{if(state.recorder?.state!=="inactive")state.recorder.stop()}catch{}state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;stopMeter();clearInterval(state.timer);updateTimer();try{state.wakeLock?.release()}catch{}state.wakeLock=null;ui();header("Sesión finalizada");insights()}
function ui(){const b=$("recordButton");b.classList.toggle("live",state.recording&&!state.paused);b.classList.toggle("paused",state.recording&&state.paused);if(!state.recording){$("recordTitle").textContent="Tocá para empezar";$("recordSubtitle").textContent=state.fragments.length?"La sesión quedó lista para revisar.":"Grabá una clase o conversación y quedate con lo importante.";$("micState").textContent="Micrófono apagado"}else if(state.paused){$("recordTitle").textContent="Grabación pausada";$("recordSubtitle").textContent="Tocá Reanudar para continuar.";$("micState").textContent="Pausado"}else{$("recordTitle").textContent="Escuchando";$("recordSubtitle").textContent="Hablá con normalidad. La app va limpiando el texto.";$("micState").textContent="Micrófono activo"}$("pauseBtn").disabled=!state.recording;$("finishBtn").disabled=!state.recording;$("pauseBtn").textContent=state.paused?"Reanudar":"Pausar"}
function meter(){try{state.audioContext=new(window.AudioContext||window.webkitAudioContext)();const src=state.audioContext.createMediaStreamSource(state.stream);state.analyser=state.audioContext.createAnalyser();state.analyser.fftSize=256;src.connect(state.analyser);const d=new Uint8Array(state.analyser.frequencyBinCount);const tick=()=>{state.analyser.getByteFrequencyData(d);$("audioLevel").style.width=Math.min(100,d.reduce((a,b)=>a+b,0)/d.length*1.8)+"%";state.frame=requestAnimationFrame(tick)};tick()}catch{}}
function stopMeter(){cancelAnimationFrame(state.frame);$("audioLevel").style.width="0%";try{state.audioContext?.close()}catch{}}
function renderRaw(){const b=$("rawTranscript");b.innerHTML=state.fragments.length?state.fragments.map(f=>'<div class="raw-row"><span class="raw-tag '+(f.keep?"keep":"skip")+'">'+(f.keep?"USAR":"OMITIR")+'</span><span>'+esc(f.text)+"</span></div>").join(""):'<span class="history-empty">Todavía no hay contenido.</span>'}
function summary(t){const s=sentences(t).filter(x=>words(x).length>=4);if(s.length<2)return"";const w=new Map(keys(t,20).map(k=>[k.word,k.count]));return s.map((sentence,index)=>({sentence,index,score:words(sentence).reduce((n,x)=>n+(w.get(x)||0),0)/Math.max(1,words(sentence).length)})).sort((a,b)=>b.score-a.score).slice(0,Math.min(4,Math.max(2,Math.ceil(s.length*.22)))).sort((a,b)=>a.index-b.index).map(x=>x.sentence).join(" ")}
function insights(){const t=text(),k=keys(t,9),manual=$("topicInput").value.trim();$("keywords").innerHTML=k.length?k.map(x=>'<span class="chip">'+esc(x.word)+"</span>").join(""):'<span class="history-empty">Sin conceptos todavía.</span>';$("detectedTopic").textContent=manual||k.slice(0,3).map(x=>x.word).join(" · ")||"Todavía no hay suficiente texto";$("summary").textContent=summary(t)||"Todavía no hay suficiente texto.";map(t,manual||k[0]?.word||"Tema principal")}
function map(t,topic){const s=sentences(t).filter(x=>words(x).length>=4),k=keys(t,16),box=$("conceptMap");if(s.length<3||k.length<3){box.innerHTML='<div class="empty-map"><strong>El mapa aparecerá cuando haya suficiente contenido.</strong><span>Usa ideas y frases, no solamente palabras sueltas.</span></div>';return}const global=new Set(k.map(x=>x.word)),branches=[];for(const key of k){if(branches.length>=5)break;const matches=s.filter(x=>words(x).includes(key.word));if(!matches.length)continue;const evidence=matches.map(x=>({x,score:words(x).filter(w=>global.has(w)).length})).sort((a,b)=>b.score-a.score)[0].x;const too=branches.some(b=>{const a=new Set(words(b.evidence)),c=new Set(words(evidence)),n=[...a].filter(x=>c.has(x)).length;return n/Math.max(1,Math.min(a.size,c.size))>.72});if(too)continue;const c=new Map;for(const x of matches)for(const w of words(x))if(w!==key.word)c.set(w,(c.get(w)||0)+1);branches.push({word:key.word,evidence,links:[...c].sort((a,b)=>b[1]-a[1]).slice(0,3).map(x=>x[0])})}box.innerHTML='<div class="map-root"><div class="map-center">'+esc(topic)+'</div><div class="map-branches">'+branches.map(b=>'<div class="map-branch"><div class="branch-title">'+esc(b.word)+'</div><div class="branch-evidence">'+esc(b.evidence)+'</div><div class="branch-links">'+b.links.map(x=>"<span>"+esc(x)+"</span>").join("")+"</div></div>").join("")+"</div></div>"}
function undo(){if(!state.fragments.length)return;state.fragments.pop();reclassify();$("undoBtn").disabled=!state.fragments.length;autosave()}
function clearText(){if(!state.fragments.length&&!text())return;if(!confirm("¿Borrar todo el texto de esta sesión?"))return;state.fragments=[];setText("");$("interimTranscript").textContent="";renderRaw();insights();$("undoBtn").disabled=true;autosave()}
function newSession(){if(state.recording){alert("Finalizá la grabación antes de crear una sesión nueva.");return}if((state.fragments.length||text())&&!confirm("¿Empezar una sesión nueva? La actual quedará guardada."))return;if(state.fragments.length||text())saveSession();state.fragments=[];state.chunks=[];state.elapsed=0;state.sessionId=null;setText("");$("rawTranscript").innerHTML="";$("interimTranscript").textContent="";$("topicInput").value="";$("timer").textContent="00:00:00";$("undoBtn").disabled=true;insights();localStorage.removeItem("escuchamapa-v3-draft");header("Listo para escuchar")}
function autosave(){localStorage.setItem("escuchamapa-v3-draft",JSON.stringify({fragments:state.fragments,topic:$("topicInput").value,language:$("languageSelect").value,elapsed:state.elapsed,updatedAt:new Date().toISOString()}))}
function restore(){try{const d=JSON.parse(localStorage.getItem("escuchamapa-v3-draft")||"null");if(!d)return;state.fragments=Array.isArray(d.fragments)?d.fragments:[];state.elapsed=d.elapsed||0;$("topicInput").value=d.topic||"";if(d.language)$("languageSelect").value=d.language;reclassify();updateTimer();$("undoBtn").disabled=!state.fragments.length}catch{}}
function history(){try{return JSON.parse(localStorage.getItem("escuchamapa-v3-history")||"[]")}catch{return[]}}
function saveSession(){const t=text();if(!t&&!state.fragments.length)return;const s={id:state.sessionId||crypto.randomUUID?.()||String(Date.now()),createdAt:new Date().toISOString(),topic:$("topicInput").value.trim(),language:$("languageSelect").value,duration:state.elapsed,fragments:state.fragments,transcript:t},h=history().filter(x=>x.id!==s.id);h.unshift(s);localStorage.setItem("escuchamapa-v3-history",JSON.stringify(h.slice(0,25)));renderHistory()}
function renderHistory(){const h=history(),b=$("historyList");if(!h.length){b.innerHTML='<span class="history-empty">No hay sesiones guardadas.</span>';return}b.innerHTML="";for(const s of h){const el=document.createElement("div");el.className="history-item";el.innerHTML='<div><strong>'+esc(s.topic||"Sesión")+'</strong><small>'+new Date(s.createdAt).toLocaleString()+" · "+format(s.duration||0)+'</small></div><div class="history-actions"><button class="ghost open">Abrir</button><button class="ghost danger del">Eliminar</button></div>';el.querySelector(".open").onclick=()=>openHistory(s.id);el.querySelector(".del").onclick=()=>deleteHistory(s.id);b.appendChild(el)}}
function openHistory(id){if(state.recording)return;const s=history().find(x=>x.id===id);if(!s)return;state.sessionId=s.id;state.fragments=s.fragments||sentences(s.transcript||"").map(text=>({text,confidence:.7,keep:true}));state.elapsed=s.duration||0;$("topicInput").value=s.topic||"";if(s.language)$("languageSelect").value=s.language;reclassify();updateTimer();$("undoBtn").disabled=!state.fragments.length;window.scrollTo({top:0,behavior:"smooth"})}
function deleteHistory(id){localStorage.setItem("escuchamapa-v3-history",JSON.stringify(history().filter(x=>x.id!==id)));renderHistory()}
function clearHistory(){if(!history().length)return;if(!confirm("¿Eliminar todo el historial?"))return;localStorage.removeItem("escuchamapa-v3-history");renderHistory()}
$("recordButton").onclick=()=>{if(!state.recording)start()};$("pauseBtn").onclick=pause;$("finishBtn").onclick=finish;$("undoBtn").onclick=undo;$("newSessionBtn").onclick=newSession;$("clearTextBtn").onclick=clearText;$("copyBtn").onclick=async()=>{try{await navigator.clipboard.writeText(text());$("copyBtn").textContent="Copiado";setTimeout(()=>$("copyBtn").textContent="Copiar",1000)}catch{}};$("toggleRawBtn").onclick=()=>{$("rawDrawer").classList.toggle("hidden");$("toggleRawBtn").textContent=$("rawDrawer").classList.contains("hidden")?"Ver todo lo escuchado":"Ocultar texto completo"};$("refreshInsightsBtn").onclick=insights;$("rebuildMapBtn").onclick=insights;$("clearHistoryBtn").onclick=clearHistory;$("topicInput").oninput=()=>{reclassify();autosave()};$("languageSelect").onchange=autosave;$("cleanTranscript").oninput=insights;
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.deferredPrompt=e;$("installBtn").classList.remove("hidden")});$("installBtn").onclick=async()=>{if(!state.deferredPrompt)return;state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null;$("installBtn").classList.add("hidden")};
document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&state.recording&&!state.paused)wake()});window.addEventListener("pagehide",()=>{if(state.fragments.length)autosave()});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(console.warn));if(!window.isSecureContext){$("compatibilityNotice").classList.remove("hidden");$("compatibilityNotice").textContent="Abrí EscuchaMapa desde HTTPS o localhost para usar el micrófono."}restore();renderRaw();renderHistory();insights();ui();